#!/usr/bin/env python3
"""Golden packet decode test for the python wire module.

Reads the committed fixtures (generated by the C++ golden_packets tool
from the protocol/ structs) and checks that telemetry_wire decodes the
exact field values the C++ side wrote. A drift between the python struct
strings and the C++ layout fails here instead of becoming a silent 100%
packet drop.

Run from anywhere: python3 software/tests/golden/test_golden.py
"""

import os
import struct
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "..", "tools"))
import telemetry_wire as tw

FIXTURES = os.path.join(os.path.dirname(__file__), "fixtures")


def f32(value: float) -> float:
    """The float32 the wire actually carries for a python literal."""
    return struct.unpack("<f", struct.pack("<f", value))[0]


def read(name: str) -> bytes:
    with open(os.path.join(FIXTURES, name), "rb") as handle:
        return handle.read()


class GoldenTelemetry(unittest.TestCase):
    def test_decode(self):
        sample = tw.decode_telemetry(read("telemetry.bin"))
        self.assertIsNotNone(sample)
        self.assertEqual(sample.source_id, tw.SOURCE_DRONE_SIM)
        self.assertEqual(sample.sequence, 0xBEEF)
        self.assertEqual(sample.timestamp_us, 1234567890123456789)
        self.assertEqual(sample.gyro_rad_s, (1.5, -2.25, 3.125))
        self.assertEqual(sample.attitude_quat, (0.5, -0.25, 0.125, -0.0625))
        self.assertEqual(sample.gyro_bias_rad_s, (0.03125, -0.0625, 0.09375))
        self.assertEqual(sample.motor, (0.125, 0.25, 0.375, 0.5))
        self.assertEqual(sample.altitude_m, 12.5)
        self.assertEqual(sample.vertical_velocity_mps, -3.5)
        self.assertEqual(sample.throw_state, 2)
        self.assertEqual(sample.throw_count, 7)
        self.assertEqual(sample.release_velocity_mps, 4.75)
        self.assertEqual(sample.apex_timestamp_us, 987654321)
        self.assertEqual(sample.apex_altitude_m, 6.25)
        self.assertEqual(sample.flight_phase, 5)
        self.assertEqual(sample.baro_altitude_m, 11.75)


class GoldenSimRaw(unittest.TestCase):
    def test_decode(self):
        sample = tw.decode_sim_raw(read("sim_raw.bin"))
        self.assertIsNotNone(sample)
        self.assertEqual(sample.source_id, tw.SOURCE_SIM_PLANT)
        self.assertEqual(sample.sequence, 0x0201)
        self.assertEqual(sample.timestamp_us, 111222333)
        self.assertEqual(sample.attitude_quat, (0.875, -0.375, 0.1875, -0.09375))
        self.assertEqual(sample.position_m, (1.5, -2.5, 3.5))
        self.assertEqual(sample.velocity_mps, (-0.5, 0.75, -1.25))


class GoldenSimLink(unittest.TestCase):
    def test_sensor(self):
        data = read("sim_sensor.bin")
        self.assertEqual(len(data), tw.SIM_SENSOR_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_SIM_SENSOR))
        fields = tw.SIM_SENSOR_STRUCT.unpack(data)
        self.assertEqual(fields[2], 555666777)  # timestamp
        self.assertEqual(fields[3:6], (0.5, -1.5, 2.5))  # gyro
        self.assertEqual(fields[6:9], (0.25, -0.75, 9.5))  # accel
        self.assertEqual(fields[9], 101325.0)  # baro
        self.assertEqual(fields[10], 9)  # reset count
        self.assertEqual(fields[11], 0xDEADBEEF)  # session id
        self.assertEqual(fields[12], 0x1234)  # lockstep timeouts

    def test_actuator(self):
        data = read("sim_actuator.bin")
        self.assertEqual(len(data), tw.SIM_ACTUATOR_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_SIM_ACTUATOR))
        fields = tw.SIM_ACTUATOR_STRUCT.unpack(data)
        self.assertEqual(fields[2], 555666777)  # echoed timestamp
        self.assertEqual(fields[3:7], (0.0625, 0.125, 0.1875, 0.25))  # motors
        # The scenario block rides in every reply, at a frozen offset.
        self.assertEqual(fields[7], 200)  # sequence
        self.assertEqual(fields[8], tw.SIM_SCENARIO_HAND_THROW)
        self.assertEqual(fields[9], 0x0123456789ABCDEF)  # seed
        self.assertEqual(fields[10], 2000000)  # throw delay
        self.assertEqual(fields[11], 16000000)  # hash window
        self.assertEqual(fields[12:15], (1.25, -2.5, 5.5))  # velocity
        self.assertEqual(fields[15:18], (-0.5, 1.5, -2.25))  # angular
        self.assertEqual(fields[18:], (1.5, 0.75, -2.5, 0.3125))  # hand throw
        # The block inside the reply is the same bytes as the standalone
        # packet carries: one layout, two carriers.
        scenario = read("sim_scenario.bin")
        self.assertEqual(
            data[tw.SIM_ACTUATOR_SCENARIO_OFFSET:],
            scenario[2:],
        )


class GoldenCommands(unittest.TestCase):
    def test_sim_scenario(self):
        data = read("sim_scenario.bin")
        self.assertEqual(len(data), tw.SIM_SCENARIO_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_SIM_SCENARIO))
        fields = tw.SIM_SCENARIO_STRUCT.unpack(data)
        self.assertEqual(fields[2], 200)  # sequence
        self.assertEqual(fields[3], tw.SIM_SCENARIO_HAND_THROW)
        self.assertEqual(fields[4], 0x0123456789ABCDEF)  # seed
        self.assertEqual(fields[5], 2000000)  # throw delay
        self.assertEqual(fields[6], 16000000)  # hash window
        self.assertEqual(fields[7:10], (1.25, -2.5, 5.5))  # velocity
        self.assertEqual(fields[10:13], (-0.5, 1.5, -2.25))  # angular
        self.assertEqual(fields[13:], (1.5, 0.75, -2.5, 0.3125))  # hand throw

    def test_encode_matches_fixture(self):
        # The encoder run by run_batch must produce the golden bytes.
        packet = tw.encode_sim_scenario(
            200, tw.SIM_SCENARIO_HAND_THROW,
            seed=0x0123456789ABCDEF,
            throw_delay_us=2000000, hash_window_us=16000000,
            velocity=(1.25, -2.5, 5.5), angular=(-0.5, 1.5, -2.25),
            held_s=1.5, held_tilt=0.75, held_azimuth=-2.5, swing_s=0.3125,
        )
        self.assertEqual(packet, read("sim_scenario.bin"))

    def test_rc_command(self):
        data = read("rc_command.bin")
        self.assertEqual(len(data), tw.RC_COMMAND_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_RC_COMMAND))
        fields = tw.RC_COMMAND_STRUCT.unpack(data)
        self.assertEqual(fields[2:5], (0, 1, tw.RC_MODE_ALTITUDE_AUTO))
        self.assertEqual(fields[5], f32(0.8125))

    def test_encode_rc_matches_fixture(self):
        # The encoder streaming RC at the flight process must produce the
        # golden bytes.
        packet = tw.encode_rc_command(
            kill=0, arm=1, mode=tw.RC_MODE_ALTITUDE_AUTO, throttle=0.8125)
        self.assertEqual(packet, read("rc_command.bin"))

    def test_reboot(self):
        data = read("reboot_command.bin")
        self.assertEqual(len(data), tw.REBOOT_COMMAND_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_REBOOT_COMMAND))
        self.assertEqual(data[2], tw.BOARD_REBOOT_MAGIC)


class GoldenAnnounce(unittest.TestCase):
    def test_decode(self):
        data = read("announce.bin")
        self.assertEqual(len(data), tw.ANNOUNCE_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_ANNOUNCE))
        fields = tw.ANNOUNCE_STRUCT.unpack(data)
        self.assertEqual(fields[2], tw.SOURCE_DRONE_SIM)
        self.assertEqual(fields[3], 0xCAFEBABE)
        self.assertEqual(fields[4], tw.TELEMETRY_PORT)
        self.assertEqual(fields[5], tw.RC_COMMAND_PORT)


class GoldenSimRunStats(unittest.TestCase):
    def test_decode(self):
        data = read("sim_run_stats.bin")
        self.assertEqual(len(data), tw.SIM_RUN_STATS_PACKET_SIZE)
        sample = tw.decode_sim_run_stats(data)
        self.assertIsNotNone(sample)
        self.assertEqual(sample.source_id, tw.SOURCE_DRONE_SIM)
        self.assertEqual(sample.sequence, 0x1337)
        self.assertEqual(sample.run_id, 23)
        self.assertEqual(sample.run_start_us, 24680135)
        self.assertEqual(sample.run_hash, 0xFEDCBA9876543210)
        self.assertEqual(sample.duplicate_frames, 11)
        self.assertEqual(sample.lockstep_timeouts, 2)
        self.assertTrue(sample.sealed)
        self.assertTrue(sample.degraded)


class GoldenTuning(unittest.TestCase):
    def test_set(self):
        fields = tw.TUNING_SET_STRUCT.unpack(read("tuning_set.bin"))
        self.assertEqual(fields, (tw.PROTOCOL_VERSION, tw.TYPE_TUNING_SET, 0x0102, 2.5))

    def test_get(self):
        fields = tw.TUNING_GET_STRUCT.unpack(read("tuning_get.bin"))
        self.assertEqual(fields, (tw.PROTOCOL_VERSION, tw.TYPE_TUNING_GET, 0x0304))

    def test_list(self):
        fields = tw.TUNING_LIST_STRUCT.unpack(read("tuning_list.bin"))
        self.assertEqual(fields, (tw.PROTOCOL_VERSION, tw.TYPE_TUNING_LIST, 5))

    def test_ack(self):
        fields = tw.TUNING_ACK_STRUCT.unpack(read("tuning_ack.bin"))
        self.assertEqual(
            fields, (tw.PROTOCOL_VERSION, tw.TYPE_TUNING_ACK, 0x0102, -1.5, 2))

    def test_info(self):
        fields = tw.TUNING_INFO_STRUCT.unpack(read("tuning_info.bin"))
        self.assertEqual(fields[:5], (tw.PROTOCOL_VERSION, tw.TYPE_TUNING_INFO, 3, 17, 0x0102))
        self.assertEqual(fields[5].rstrip(b"\x00"), b"rate_kp")
        self.assertEqual(fields[6:], (0.09375, 0.0, 1.5, 1))


#: The session nonce every OTA fixture of the one session echoes.
OTA_SESSION = 0x1A2B3C4D
#: Offset and payload of the fixture chunk (fewer bytes than the maximum).
OTA_CHUNK_OFFSET = 275040
OTA_CHUNK_DATA = bytes([0xDE, 0xAD, 0xBE, 0xEF, 0x2A])
#: Image size announced by the begin and stamped in the image header.
OTA_IMAGE_SIZE = 0x00021308


class GoldenCrc32Mpeg2(unittest.TestCase):
    """The one checksum of the update system, against known vectors.

    These come from the CRC-32/MPEG-2 the F405 hardware unit computes over
    the same words; the odd-length vector exercises the 0xFF tail padding
    the image convention mandates.
    """

    def test_known_vectors(self):
        self.assertEqual(tw.crc32_mpeg2(bytes(4)), 0xC704DD7B)
        self.assertEqual(tw.crc32_mpeg2(bytes([1, 2, 3, 4, 5, 6, 7, 8])), 0xA3141BDA)
        self.assertEqual(tw.crc32_mpeg2(bytes([1, 2, 3, 4, 5])), 0xCCD0E62C)

    def test_padding_is_not_zero_padding(self):
        # 0xFF, not 0x00: a zero-padded tail would give another answer.
        self.assertEqual(
            tw.crc32_mpeg2(bytes([1, 2, 3, 4, 5])),
            tw.crc32_mpeg2(bytes([1, 2, 3, 4, 5, 0xFF, 0xFF, 0xFF])),
        )


class GoldenOta(unittest.TestCase):
    """The update packets: hub to board and back, never near Godot."""

    def test_status_request(self):
        data = read("ota_status_request.bin")
        self.assertEqual(len(data), tw.OTA_STATUS_REQUEST_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_OTA_STATUS_REQUEST))
        self.assertEqual(tw.encode_ota_status_request(), data)

    def test_status(self):
        data = read("ota_status.bin")
        self.assertEqual(len(data), tw.OTA_STATUS_PACKET_SIZE)
        status = tw.decode_ota_status(data)
        self.assertIsNotNone(status)
        self.assertEqual(status.mcu_id, tw.OTA_MCU_STM32F405)
        self.assertEqual(status.running_slot, tw.OTA_SLOT_B)
        self.assertEqual(status.active_slot, tw.OTA_SLOT_A)
        self.assertEqual(status.updater_busy, 0)
        self.assertEqual(status.slots[0].state, tw.OTA_SLOT_VALID)
        self.assertEqual(status.slots[0].build_epoch, 0x66E42F01)
        self.assertEqual(status.slots[0].git_hash, b"cafe0001")
        self.assertEqual(status.slots[1].state, tw.OTA_SLOT_TESTING)
        self.assertEqual(status.slots[1].build_epoch, 0x66E43D95)
        self.assertEqual(status.slots[1].git_hash, b"deadbeef")
        self.assertEqual(status.slot_size, 0x00060102)
        self.assertEqual(status.max_chunk_data, tw.OTA_CHUNK_DATA_SIZE)
        self.assertEqual(tw.encode_ota_status(status), data)

    def test_begin(self):
        data = read("ota_begin.bin")
        self.assertEqual(len(data), tw.OTA_BEGIN_PACKET_SIZE)
        fields = tw.OTA_BEGIN_STRUCT.unpack(data)
        self.assertEqual(
            fields,
            (tw.PROTOCOL_VERSION, tw.TYPE_OTA_BEGIN, OTA_SESSION, OTA_IMAGE_SIZE, 0x89ABCDEF),
        )
        self.assertEqual(
            tw.encode_ota_begin(OTA_SESSION, OTA_IMAGE_SIZE, 0x89ABCDEF), data)

    def test_chunk(self):
        data = read("ota_chunk.bin")
        self.assertEqual(len(data), tw.OTA_CHUNK_PACKET_SIZE)
        chunk = tw.decode_ota_chunk(data)
        self.assertIsNotNone(chunk)
        self.assertEqual(chunk.session, OTA_SESSION)
        self.assertEqual(chunk.offset, OTA_CHUNK_OFFSET)
        # Short on purpose: the length byte, not the packet size, says how
        # many bytes are image bytes.
        self.assertEqual(chunk.data, OTA_CHUNK_DATA)
        self.assertLess(len(chunk.data), tw.OTA_CHUNK_DATA_SIZE)
        self.assertEqual(
            tw.OTA_CHUNK_STRUCT.unpack(data)[5],
            OTA_CHUNK_DATA + bytes(tw.OTA_CHUNK_DATA_SIZE - len(OTA_CHUNK_DATA)),
        )
        self.assertEqual(
            tw.encode_ota_chunk(OTA_SESSION, OTA_CHUNK_OFFSET, OTA_CHUNK_DATA), data)

    def test_chunk_ack(self):
        data = read("ota_chunk_ack.bin")
        self.assertEqual(len(data), tw.OTA_CHUNK_ACK_PACKET_SIZE)
        ack = tw.decode_ota_chunk_ack(data)
        self.assertIsNotNone(ack)
        self.assertEqual(ack.session, OTA_SESSION)
        # Cumulative: the fixture chunk landed, its last byte included.
        self.assertEqual(ack.next_offset, OTA_CHUNK_OFFSET + len(OTA_CHUNK_DATA))
        self.assertEqual(
            tw.encode_ota_chunk_ack(ack.session, ack.next_offset), data)

    def test_finish(self):
        data = read("ota_finish.bin")
        self.assertEqual(len(data), tw.OTA_FINISH_PACKET_SIZE)
        self.assertEqual(
            tw.OTA_FINISH_STRUCT.unpack(data),
            (tw.PROTOCOL_VERSION, tw.TYPE_OTA_FINISH, OTA_SESSION),
        )
        self.assertEqual(tw.encode_ota_finish(OTA_SESSION), data)

    def test_confirm(self):
        data = read("ota_confirm.bin")
        self.assertEqual(len(data), tw.OTA_CONFIRM_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_OTA_CONFIRM))
        self.assertEqual(tw.encode_ota_confirm(), data)

    def test_revert(self):
        data = read("ota_revert.bin")
        self.assertEqual(len(data), tw.OTA_REVERT_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_OTA_REVERT))
        self.assertEqual(tw.encode_ota_revert(), data)

    def test_abort(self):
        data = read("ota_abort.bin")
        self.assertEqual(len(data), tw.OTA_ABORT_PACKET_SIZE)
        self.assertEqual(
            tw.OTA_ABORT_STRUCT.unpack(data),
            (tw.PROTOCOL_VERSION, tw.TYPE_OTA_ABORT, OTA_SESSION),
        )
        self.assertEqual(tw.encode_ota_abort(OTA_SESSION), data)

    def test_ack(self):
        data = read("ota_ack.bin")
        self.assertEqual(len(data), tw.OTA_ACK_PACKET_SIZE)
        ack = tw.decode_ota_ack(data)
        self.assertIsNotNone(ack)
        self.assertEqual(ack.session, OTA_SESSION)
        self.assertEqual(ack.acked_type, tw.TYPE_OTA_FINISH)
        self.assertEqual(ack.result, tw.OTA_RESULT_CRC_MISMATCH)
        self.assertFalse(ack.ok)
        self.assertEqual(
            tw.encode_ota_ack(ack.session, ack.acked_type, ack.result), data)

    def test_image_header(self):
        data = read("ota_image_header.bin")
        self.assertEqual(len(data), tw.OTA_IMAGE_HEADER_SIZE)
        header = tw.decode_ota_image_header(data)
        self.assertIsNotNone(header)
        self.assertEqual(header.magic, tw.OTA_IMAGE_MAGIC)
        self.assertEqual(data[:4], b"M4FW")
        self.assertEqual(header.header_version, tw.OTA_IMAGE_HEADER_VERSION)
        self.assertEqual(header.mcu_id, tw.OTA_MCU_STM32F722)
        self.assertEqual(header.slot_id, tw.OTA_SLOT_A)
        self.assertEqual(header.image_size, OTA_IMAGE_SIZE)
        self.assertEqual(header.image_crc, 0x76543210)
        self.assertEqual(header.build_epoch, 0x66E43D95)
        self.assertEqual(header.git_hash, b"0badc0de")
        # The C++ side stamped this crc: reproducing it is the check that
        # the python packaging script and the bootloader agree bit for bit.
        self.assertEqual(header.header_crc, tw.crc32_mpeg2(data[:508]))
        self.assertEqual(
            tw.encode_ota_image_header(
                tw.OTA_MCU_STM32F722, tw.OTA_SLOT_A, OTA_IMAGE_SIZE, 0x76543210,
                build_epoch=0x66E43D95, git_hash=b"0badc0de",
            ),
            data,
        )

    def test_image_header_rejects_a_broken_crc(self):
        data = bytearray(read("ota_image_header.bin"))
        data[16] ^= 0x01  # one flipped bit in the build epoch
        self.assertFalse(tw.valid_ota_image_header(bytes(data)))
        self.assertIsNone(tw.decode_ota_image_header(bytes(data)))


class GoldenSerialFrame(unittest.TestCase):
    def test_encode(self):
        self.assertEqual(
            tw.encode_serial_frame(bytes([0x01, 0x02, 0x03, 0x04, 0xFA])),
            read("serial_frame.bin"),
        )


if __name__ == "__main__":
    unittest.main()
