extends SceneTree

## Golden packet decode check for the GDScript side.
##
## Reads the committed fixtures (generated by the C++ golden_packets tool
## from the protocol/ structs) and decodes them with the same constants
## and offsets the runtime scripts use (all read from protocol.gd, the
## single GDScript copy), so a drift between protocol.gd
## and the C++ layout fails here instead of becoming a silent 100%
## packet drop in the simulator.
##
## Run from the repo root:
##   godot --path sim-godot --headless --script res://tests/golden_check.gd \
##     -- <absolute path of tests/golden/fixtures>

var failures: int = 0


func _init() -> void:
	var args := OS.get_cmdline_user_args()
	if args.is_empty():
		push_error("golden check: fixtures directory argument missing")
		quit(2)
		return
	var fixtures: String = args[0]

	_check_actuator(fixtures)
	_check_telemetry(fixtures)
	_check_sensor_and_raw_sizes(fixtures)
	_check_sim_command(fixtures)

	if failures == 0:
		print("golden check: GDScript decodes every fixture")
		quit(0)
	else:
		push_error("golden check: %d failure(s)" % failures)
		quit(1)


func _expect(condition: bool, what: String) -> void:
	if not condition:
		push_error("golden check: %s" % what)
		failures += 1


func _read(fixtures: String, name: String) -> PackedByteArray:
	var payload := FileAccess.get_file_as_bytes(fixtures.path_join(name))
	_expect(not payload.is_empty(), "cannot read %s" % name)
	return payload


## The actuator packet is what SimLink decodes every physics tick.
func _check_actuator(fixtures: String) -> void:
	var payload := _read(fixtures, "sim_actuator.bin")
	_expect(payload.size() == Protocol.SIM_ACTUATOR_PACKET_SIZE, "actuator size")
	_expect(Protocol.has_header(payload, Protocol.TYPE_SIM_ACTUATOR), "actuator header")
	_expect(payload.decode_u64(Protocol.SIM_ACTUATOR_ECHO_OFFSET) == 555666777, "actuator echo")
	var motors := [0.0625, 0.125, 0.1875, 0.25]
	for index: int in 4:
		var offset: int = Protocol.SIM_ACTUATOR_MOTOR_OFFSET + index * Protocol.FLOAT_SIZE
		_expect(payload.decode_float(offset) == motors[index], "actuator motor %d" % index)


## The telemetry quaternion is what AttitudeCompare reads for the ghost.
func _check_telemetry(fixtures: String) -> void:
	var payload := _read(fixtures, "telemetry.bin")
	_expect(payload.size() == Protocol.TELEMETRY_PACKET_SIZE, "telemetry size")
	_expect(Protocol.has_header(payload, Protocol.TYPE_TELEMETRY), "telemetry header")
	var quat := [0.5, -0.25, 0.125, -0.0625]
	for index: int in 4:
		var offset: int = Protocol.TELEMETRY_QUAT_OFFSET + index * Protocol.FLOAT_SIZE
		_expect(payload.decode_float(offset) == quat[index], "telemetry quat %d" % index)


## The packets Godot produces: their frozen sizes and headers must match
## what the pack code in sim_link.gd and sim_raw_link.gd builds.
func _check_sensor_and_raw_sizes(fixtures: String) -> void:
	var sensor := _read(fixtures, "sim_sensor.bin")
	_expect(sensor.size() == Protocol.SIM_SENSOR_PACKET_SIZE, "sensor size")
	_expect(Protocol.has_header(sensor, Protocol.TYPE_SIM_SENSOR), "sensor header")
	var raw := _read(fixtures, "sim_raw.bin")
	_expect(raw.size() == Protocol.SIM_RAW_PACKET_SIZE, "sim raw size")
	_expect(Protocol.has_header(raw, Protocol.TYPE_SIM_RAW), "sim raw header")


## The command packet is what SimCommand decodes for batch campaigns.
func _check_sim_command(fixtures: String) -> void:
	var payload := _read(fixtures, "sim_command.bin")
	_expect(payload.size() == Protocol.SIM_COMMAND_PACKET_SIZE, "command size")
	_expect(Protocol.has_header(payload, Protocol.TYPE_SIM_COMMAND), "command header")
	_expect(payload.decode_u8(2) == Protocol.SIM_COMMAND_HAND_THROW, "command byte")
	_expect(payload.decode_float(Protocol.SIM_COMMAND_THROTTLE_OFFSET) == 0.375, "command throttle")
	var velocity := [1.25, -2.5, 5.5]
	var angular := [-0.5, 1.5, -2.25]
	for index: int in 3:
		var v_offset: int = Protocol.SIM_COMMAND_VELOCITY_OFFSET + index * 4
		var a_offset: int = Protocol.SIM_COMMAND_ANGULAR_OFFSET + index * 4
		_expect(payload.decode_float(v_offset) == velocity[index], "command velocity %d" % index)
		_expect(payload.decode_float(a_offset) == angular[index], "command angular %d" % index)
	var hand := [1.5, 0.75, -2.5, 0.3125]
	for index: int in 4:
		var offset: int = Protocol.SIM_COMMAND_HELD_OFFSET + index * 4
		_expect(payload.decode_float(offset) == hand[index], "command hand field %d" % index)
