extends SceneTree

## Golden packet decode check for the GDScript side.
##
## Reads the committed fixtures (generated by the C++ golden_packets tool
## from the protocol/ structs) and decodes them with the same constants
## and offsets the runtime scripts use (all read from protocol.gd, the
## single GDScript copy), so a drift between protocol.gd
## and the C++ layout fails here instead of becoming a silent 100%
## packet drop in the simulator.
##
## Run from the repo root:
##   godot --path sim-godot --headless --script res://tests/golden_check.gd \
##     -- <absolute path of tests/golden/fixtures>

var failures: int = 0


func _init() -> void:
	var args := OS.get_cmdline_user_args()
	if args.is_empty():
		push_error("golden check: fixtures directory argument missing")
		quit(2)
		return
	var fixtures: String = args[0]

	_check_actuator(fixtures)
	_check_sensor_and_raw_sizes(fixtures)
	_check_scenario_in_actuator(fixtures)

	if failures == 0:
		print("golden check: GDScript decodes every fixture")
		quit(0)
	else:
		push_error("golden check: %d failure(s)" % failures)
		quit(1)


func _expect(condition: bool, what: String) -> void:
	if not condition:
		push_error("golden check: %s" % what)
		failures += 1


func _read(fixtures: String, name: String) -> PackedByteArray:
	var payload := FileAccess.get_file_as_bytes(fixtures.path_join(name))
	_expect(not payload.is_empty(), "cannot read %s" % name)
	return payload


## The actuator packet is what SimLink decodes every physics tick.
func _check_actuator(fixtures: String) -> void:
	var payload := _read(fixtures, "sim_actuator.bin")
	_expect(payload.size() == Protocol.SIM_ACTUATOR_PACKET_SIZE, "actuator size")
	_expect(Protocol.has_header(payload, Protocol.TYPE_SIM_ACTUATOR), "actuator header")
	_expect(payload.decode_u64(Protocol.SIM_ACTUATOR_ECHO_OFFSET) == 555666777, "actuator echo")
	var motors := [0.0625, 0.125, 0.1875, 0.25]
	for index: int in 4:
		var offset: int = Protocol.SIM_ACTUATOR_MOTOR_OFFSET + index * Protocol.FLOAT_SIZE
		_expect(payload.decode_float(offset) == motors[index], "actuator motor %d" % index)


## The packets Godot produces: their frozen sizes and headers must match
## what the pack code in sim_link.gd and sim_raw_link.gd builds.
func _check_sensor_and_raw_sizes(fixtures: String) -> void:
	var sensor := _read(fixtures, "sim_sensor.bin")
	_expect(sensor.size() == Protocol.SIM_SENSOR_PACKET_SIZE, "sensor size")
	_expect(Protocol.has_header(sensor, Protocol.TYPE_SIM_SENSOR), "sensor header")
	var raw := _read(fixtures, "sim_raw.bin")
	_expect(raw.size() == Protocol.SIM_RAW_PACKET_SIZE, "sim raw size")
	_expect(Protocol.has_header(raw, Protocol.TYPE_SIM_RAW), "sim raw header")


## The scenario block is decoded OUT of the lockstep reply: that is the
## only path this project ever parses a scenario on, so it is the one the
## fixtures have to guard.
func _check_scenario_in_actuator(fixtures: String) -> void:
	var payload := _read(fixtures, "sim_actuator.bin")
	var base: int = Protocol.SIM_ACTUATOR_SCENARIO_OFFSET
	_expect(payload.size() == base + Protocol.SIM_SCENARIO_SIZE, "scenario block fits the reply")
	_expect(payload.decode_u8(base) == 200, "scenario sequence")
	_expect(payload.decode_u8(base + 1) == Protocol.SIM_SCENARIO_HAND_THROW, "scenario byte")
	# decode_u64 is signed in GDScript; the fixture seed fits a positive one.
	_expect(payload.decode_u64(base + Protocol.SCENARIO_SEED_OFFSET) == 81985529216486895,
		"scenario seed")
	_expect(payload.decode_u32(base + Protocol.SCENARIO_THROW_DELAY_OFFSET) == 2000000,
		"scenario throw delay")
	var velocity := [1.25, -2.5, 5.5]
	var angular := [-0.5, 1.5, -2.25]
	for index: int in 3:
		var v_offset: int = base + Protocol.SCENARIO_VELOCITY_OFFSET + index * Protocol.FLOAT_SIZE
		var a_offset: int = base + Protocol.SCENARIO_ANGULAR_OFFSET + index * Protocol.FLOAT_SIZE
		_expect(payload.decode_float(v_offset) == velocity[index], "scenario velocity %d" % index)
		_expect(payload.decode_float(a_offset) == angular[index], "scenario angular %d" % index)
	var hand := [1.5, 0.75, -2.5, 0.3125]
	for index: int in 4:
		var offset: int = base + Protocol.SCENARIO_HELD_OFFSET + index * Protocol.FLOAT_SIZE
		_expect(payload.decode_float(offset) == hand[index], "scenario hand field %d" % index)
