#!/usr/bin/env bash
# Generates everything under lib/gen/ (gitignored), from the sources of truth
# elsewhere in the repository:
#   - mark4.pb*.dart: the Dart codec of software/components/protocol/mark4.proto
#     (protoc from grpcio-tools, the image has no system protoc; the Dart
#     plugin from the pubspec)
#   - wire_hash.dart: the first 8 hex characters of the SHA-256 of mark4.proto,
#     the same value CMake bakes into every C++ node
#   - transport_bindings.dart: the dart:ffi binding of native/include/mark4/
#     transport_shim.h, by ffigen
# Run after `flutter pub get`; every flutter analyze / test / build needs it.
set -euo pipefail
cd "$(dirname "$0")/.."

PROTO_DIR=../components/protocol
GEN_DIR=lib/gen
mkdir -p "$GEN_DIR"

python3 -m grpc_tools.protoc -I "$PROTO_DIR" \
    --plugin=protoc-gen-dart=tool/protoc-gen-dart \
    --dart_out="$GEN_DIR" mark4.proto

hash=$(sha256sum "$PROTO_DIR/mark4.proto" | cut -c1-8)
cat > "$GEN_DIR/wire_hash.dart" <<DART
// Generated by tool/gen.sh from software/components/protocol/mark4.proto.
// Do not edit.

/// First 8 hex characters of the SHA-256 of mark4.proto: what this build
/// speaks. Every Announce carries it, the hub flags a mismatch.
const int wireHash = 0x$hash;
DART

dart run ffigen --config ffigen.yaml
