#!/usr/bin/env python3
"""Golden packet decode test for the python wire module.

Reads the committed fixtures (generated by the C++ golden_packets tool
from the protocol/ structs) and checks that telemetry_wire decodes the
exact field values the C++ side wrote. A drift between the python struct
strings and the C++ layout fails here instead of becoming a silent 100%
packet drop.

Run from anywhere: python3 tests/golden/test_golden.py
"""

import os
import struct
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "tools"))
import telemetry_wire as tw

FIXTURES = os.path.join(os.path.dirname(__file__), "fixtures")


def f32(value: float) -> float:
    """The float32 the wire actually carries for a python literal."""
    return struct.unpack("<f", struct.pack("<f", value))[0]


def read(name: str) -> bytes:
    with open(os.path.join(FIXTURES, name), "rb") as handle:
        return handle.read()


class GoldenTelemetry(unittest.TestCase):
    def test_decode(self):
        sample = tw.decode_telemetry(read("telemetry.bin"))
        self.assertIsNotNone(sample)
        self.assertEqual(sample.source_id, tw.SOURCE_DRONE_SIM)
        self.assertEqual(sample.sequence, 0xBEEF)
        self.assertEqual(sample.timestamp_us, 1234567890123456789)
        self.assertEqual(sample.gyro_rad_s, (1.5, -2.25, 3.125))
        self.assertEqual(sample.attitude_quat, (0.5, -0.25, 0.125, -0.0625))
        self.assertEqual(sample.gyro_bias_rad_s, (0.03125, -0.0625, 0.09375))
        self.assertEqual(sample.motor, (0.125, 0.25, 0.375, 0.5))
        self.assertEqual(sample.altitude_m, 12.5)
        self.assertEqual(sample.vertical_velocity_mps, -3.5)
        self.assertEqual(sample.throw_state, 2)
        self.assertEqual(sample.throw_count, 7)
        self.assertEqual(sample.release_velocity_mps, 4.75)
        self.assertEqual(sample.apex_timestamp_us, 987654321)
        self.assertEqual(sample.apex_altitude_m, 6.25)
        self.assertEqual(sample.flight_phase, 5)


class GoldenSimRaw(unittest.TestCase):
    def test_decode(self):
        sample = tw.decode_sim_raw(read("sim_raw.bin"))
        self.assertIsNotNone(sample)
        self.assertEqual(sample.source_id, tw.SOURCE_SIM_PLANT)
        self.assertEqual(sample.sequence, 0x0201)
        self.assertEqual(sample.timestamp_us, 111222333)
        self.assertEqual(sample.attitude_quat, (0.875, -0.375, 0.1875, -0.09375))
        self.assertEqual(sample.position_m, (1.5, -2.5, 3.5))
        self.assertEqual(sample.velocity_mps, (-0.5, 0.75, -1.25))


class GoldenSimLink(unittest.TestCase):
    def test_sensor(self):
        data = read("sim_sensor.bin")
        self.assertEqual(len(data), tw.SIM_SENSOR_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_SIM_SENSOR))
        fields = tw.SIM_SENSOR_STRUCT.unpack(data)
        self.assertEqual(fields[2], 555666777)  # timestamp
        self.assertEqual(fields[3:6], (0.5, -1.5, 2.5))  # gyro
        self.assertEqual(fields[6:9], (0.25, -0.75, 9.5))  # accel
        self.assertEqual(fields[9], 101325.0)  # baro
        self.assertEqual(fields[10], 9)  # reset count
        self.assertEqual(fields[11], 0xDEADBEEF)  # session id
        self.assertEqual(fields[12], 0x1234)  # lockstep timeouts

    def test_actuator(self):
        data = read("sim_actuator.bin")
        self.assertEqual(len(data), tw.SIM_ACTUATOR_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_SIM_ACTUATOR))
        fields = tw.SIM_ACTUATOR_STRUCT.unpack(data)
        self.assertEqual(fields[2], 555666777)  # echoed timestamp
        self.assertEqual(fields[3:7], (0.0625, 0.125, 0.1875, 0.25))  # motors
        # The scenario block rides in every reply, at a frozen offset.
        self.assertEqual(fields[7], 200)  # sequence
        self.assertEqual(fields[8], tw.SIM_SCENARIO_HAND_THROW)
        self.assertEqual(fields[9], 0x0123456789ABCDEF)  # seed
        self.assertEqual(fields[10], 2000000)  # throw delay
        self.assertEqual(fields[11], 16000000)  # hash window
        self.assertEqual(fields[12:15], (1.25, -2.5, 5.5))  # velocity
        self.assertEqual(fields[15:18], (-0.5, 1.5, -2.25))  # angular
        self.assertEqual(fields[18:], (1.5, 0.75, -2.5, 0.3125))  # hand throw
        # The block inside the reply is the same bytes as the standalone
        # packet carries: one layout, two carriers.
        scenario = read("sim_scenario.bin")
        self.assertEqual(
            data[tw.SIM_ACTUATOR_SCENARIO_OFFSET:],
            scenario[2:],
        )


class GoldenCommands(unittest.TestCase):
    def test_sim_scenario(self):
        data = read("sim_scenario.bin")
        self.assertEqual(len(data), tw.SIM_SCENARIO_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_SIM_SCENARIO))
        fields = tw.SIM_SCENARIO_STRUCT.unpack(data)
        self.assertEqual(fields[2], 200)  # sequence
        self.assertEqual(fields[3], tw.SIM_SCENARIO_HAND_THROW)
        self.assertEqual(fields[4], 0x0123456789ABCDEF)  # seed
        self.assertEqual(fields[5], 2000000)  # throw delay
        self.assertEqual(fields[6], 16000000)  # hash window
        self.assertEqual(fields[7:10], (1.25, -2.5, 5.5))  # velocity
        self.assertEqual(fields[10:13], (-0.5, 1.5, -2.25))  # angular
        self.assertEqual(fields[13:], (1.5, 0.75, -2.5, 0.3125))  # hand throw

    def test_encode_matches_fixture(self):
        # The encoder run by run_batch must produce the golden bytes.
        packet = tw.encode_sim_scenario(
            200, tw.SIM_SCENARIO_HAND_THROW,
            seed=0x0123456789ABCDEF,
            throw_delay_us=2000000, hash_window_us=16000000,
            velocity=(1.25, -2.5, 5.5), angular=(-0.5, 1.5, -2.25),
            held_s=1.5, held_tilt=0.75, held_azimuth=-2.5, swing_s=0.3125,
        )
        self.assertEqual(packet, read("sim_scenario.bin"))

    def test_rc_command(self):
        data = read("rc_command.bin")
        self.assertEqual(len(data), tw.RC_COMMAND_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_RC_COMMAND))
        fields = tw.RC_COMMAND_STRUCT.unpack(data)
        self.assertEqual(fields[2:5], (0, 1, tw.RC_MODE_ALTITUDE_AUTO))
        self.assertEqual(fields[5], f32(0.8125))

    def test_encode_rc_matches_fixture(self):
        # The encoder streaming RC at the flight process must produce the
        # golden bytes.
        packet = tw.encode_rc_command(
            kill=0, arm=1, mode=tw.RC_MODE_ALTITUDE_AUTO, throttle=0.8125)
        self.assertEqual(packet, read("rc_command.bin"))

    def test_reboot(self):
        data = read("reboot_command.bin")
        self.assertEqual(len(data), tw.REBOOT_COMMAND_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_REBOOT_COMMAND))
        self.assertEqual(data[2], tw.BOARD_REBOOT_MAGIC)


class GoldenAnnounce(unittest.TestCase):
    def test_decode(self):
        data = read("announce.bin")
        self.assertEqual(len(data), tw.ANNOUNCE_PACKET_SIZE)
        self.assertTrue(tw.has_header(data, tw.TYPE_ANNOUNCE))
        fields = tw.ANNOUNCE_STRUCT.unpack(data)
        self.assertEqual(fields[2], tw.SOURCE_DRONE_SIM)
        self.assertEqual(fields[3], 0xCAFEBABE)
        self.assertEqual(fields[4], tw.TELEMETRY_PORT)
        self.assertEqual(fields[5], tw.RC_COMMAND_PORT)


class GoldenSimRunStats(unittest.TestCase):
    def test_decode(self):
        data = read("sim_run_stats.bin")
        self.assertEqual(len(data), tw.SIM_RUN_STATS_PACKET_SIZE)
        sample = tw.decode_sim_run_stats(data)
        self.assertIsNotNone(sample)
        self.assertEqual(sample.source_id, tw.SOURCE_DRONE_SIM)
        self.assertEqual(sample.sequence, 0x1337)
        self.assertEqual(sample.run_id, 23)
        self.assertEqual(sample.run_start_us, 24680135)
        self.assertEqual(sample.run_hash, 0xFEDCBA9876543210)
        self.assertEqual(sample.duplicate_frames, 11)
        self.assertEqual(sample.lockstep_timeouts, 2)
        self.assertTrue(sample.sealed)
        self.assertTrue(sample.degraded)


class GoldenTuning(unittest.TestCase):
    def test_set(self):
        fields = tw.TUNING_SET_STRUCT.unpack(read("tuning_set.bin"))
        self.assertEqual(fields, (tw.PROTOCOL_VERSION, tw.TYPE_TUNING_SET, 0x0102, 2.5))

    def test_get(self):
        fields = tw.TUNING_GET_STRUCT.unpack(read("tuning_get.bin"))
        self.assertEqual(fields, (tw.PROTOCOL_VERSION, tw.TYPE_TUNING_GET, 0x0304))

    def test_list(self):
        fields = tw.TUNING_LIST_STRUCT.unpack(read("tuning_list.bin"))
        self.assertEqual(fields, (tw.PROTOCOL_VERSION, tw.TYPE_TUNING_LIST, 5))

    def test_ack(self):
        fields = tw.TUNING_ACK_STRUCT.unpack(read("tuning_ack.bin"))
        self.assertEqual(
            fields, (tw.PROTOCOL_VERSION, tw.TYPE_TUNING_ACK, 0x0102, -1.5, 2))

    def test_info(self):
        fields = tw.TUNING_INFO_STRUCT.unpack(read("tuning_info.bin"))
        self.assertEqual(fields[:5], (tw.PROTOCOL_VERSION, tw.TYPE_TUNING_INFO, 3, 17, 0x0102))
        self.assertEqual(fields[5].rstrip(b"\x00"), b"rate_kp")
        self.assertEqual(fields[6:], (0.09375, 0.0, 1.5, 1))


class GoldenBlackbox(unittest.TestCase):
    def test_decode(self):
        data = read("blackbox_record.bin")
        self.assertEqual(len(data), tw.BLACKBOX_RECORD_SIZE)
        self.assertTrue(tw.valid_blackbox_record(data))
        records = list(tw.iter_blackbox_records(data))
        self.assertEqual(len(records), 1)
        r = records[0]
        self.assertEqual(r[5], 987654321)  # timestamp
        self.assertEqual(r[6:9], (0.25, -0.5, 1.5))  # gyro
        self.assertEqual(r[9:12], (0.0, 0.0, f32(9.80665)))  # accel
        self.assertEqual(r[12], 101325.0)  # baro
        self.assertEqual(r[13], 0)  # kill
        self.assertEqual(r[14], 0.75)  # throttle
        self.assertEqual(r[15], 1)  # arm
        self.assertEqual(r[16:20], (0.125, 0.25, 0.5, 0.75))  # motors


class GoldenSerialFrame(unittest.TestCase):
    def test_encode(self):
        self.assertEqual(
            tw.encode_serial_frame(bytes([0x01, 0x02, 0x03, 0x04, 0xFA])),
            read("serial_frame.bin"),
        )


if __name__ == "__main__":
    unittest.main()
